version: '3.8'

services:
  # --- BASE DE DATOS ---
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '0.5'     # Máximo 50% de un núcleo
          memory: 2GB    # Máximo 256MB de RAM
        reservations:
          memory: 512MB    # Garantiza al menos esto al arrancar
    restart: always
  # --- BACKEND (Django) ---
  backend:
    build: ./backend  # Ruta a tu carpeta con el Dockerfile de Django
    restart: always
    environment:
      - RUNNING_IN_DOCKER=True
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/code
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.8'     # Máximo 80% de un núcleo
          memory: 2GB    # Django suele pedir un poco más que la DB
        reservations:
          memory: 512MB
    ports:
      - "8000:8000" # Esto mapea el puerto del servidor al contenedor

  # --- FRONTEND (React + Nginx) ---
  frontend:
    build: ./frontend # Ruta a tu carpeta con el Dockerfile de React
    restart: always
    ports:
      - "80:80"       # Abrimos el puerto 80 al mundo
      - "443:443"     # Abrimos el puerto 443 para HTTPS
    volumes:
      # Sobreescribimos la config de Nginx con la nuestra
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Compartimos los certificados con Certbot
      - certs:/etc/letsencrypt
      - certs-data:/var/www/certbot
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 1GB    # Nginx sirviendo React es muy ligero

  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/var/www/certbot
    # Comando para obtener el certificado inicial
    command: certonly --webroot --webroot-path=/var/www/certbot --email niccord33@gmail.com --agree-tos --no-eff-email -d staskm.online

volumes:
  postgres_data:
  certs:
  certs-data:
